### 

POST http://localhost:8080/api/polls HTTP/1.1

{
  "description": "...",
  "options": [
    "Movie 1",
    "Movie 2",
    "Movie 3",
    "Movie 4",
    "Movie 5"
  ],
  "title": "Whats the best movie of 2025?"
}


### 

GET http://localhost:8080/api/polls/f87fe4b5-afad-4498-ae18-42e9e0635fba HTTP/1.1


### 

POST http://localhost:8080/api/polls/f87fe4b5-afad-4498-ae18-42e9e0635fba/votes HTTP/1.1

{
  "option_id": "d275212d-8590-4767-9905-d7ec1915dcc6"
}
